www/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('app.index');
});

Route::group(['prefix' => 'api/v1', 'middleware' => ['cors']], function () {
    Route::get('orders', 'ApiController@index');
    Route::post('order', 'ApiController@store');
    Route::get('order/{order}', 'ApiController@getOrder');
    Route::get('bar/{user}', 'ApiController@getBar');
    Route::get('drinks/{user}', 'ApiController@getDrinks');
    Route::get('categories/{user}', 'ApiController@getCategories');
    Route::get('category/{id}', 'ApiController@getCategory');
    Route::get('popular/{id}', 'ApiController@getPopular');
    Route::get('sales/{id}', 'ApiController@getSales');
});

Route::group(['prefix' => 'backoffice/api/v1', 'middleware' => ['web']], function () {
    Route::resource('orders', 'Api\Backoffice\OrderController');
    // Route::resource('bar.orders', 'Api\Backoffice\OrderController', [
    //     'parameters' => 'singular'
    // ]);
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    // Backoffice
    Route::resource('categories', 'CategoryController');
    Route::resource('drinks', 'DrinkController');
    Route::resource('bar', 'BarController');
    Route::get('drinks/create/{categoryId}', 'DrinkController@create');
    Route::get('orders/{tab}', 'OrderController@index')->name('orders.index');
    Route::get('orders', 'OrderController@show')->name('orders.show');
    Route::get('orders/create', 'OrderController@create')->name('orders.create');
    Route::patch('orders', 'OrderController@update')->name('orders.update');
});

www/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'user_id'];

    public function drinks()
    {
        return $this->hasMany('App\Drink');
    }

    public function user()
    {
		return $this->belongsTo('App\User');
    }
}

www/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Auth;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class CategoryController extends Controller
{
	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		/**
		 * Get the first category and show it
		 */
		$category = \Auth::user()->categories()->first();
		return redirect()->action('CategoryController@show', [$category->id]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('category.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		// TODO: category validation
		$this->validate($request, [
			'name' => 'required',
			'image' => 'required',
		]);

		$input = $request->all();
        $input['user_id'] = Auth::user()->id;
		$category = Category::create($input);

		if($request->hasFile('image')) {
            $file = Input::file('image');
            $extension = Input::file('image')->getClientOriginalExtension();

            $name = 'category_' . $category->id . '.' . $extension;

            $category->image = \App::make('url')->to('/') . '/images/' . $name;

            $file->move(public_path().'/images/', $name);
        }

        $category->save();

		return redirect()->action('CategoryController@show', [$category->id]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$category = Category::findOrFail($id);

		$user = Auth::user();
		if($category->user_id != $user->id) return response()->view('errors.404', [], 404);

		$drinks = $category->drinks()->get();
		$categories = \Auth::user()->categories()->get();
		return view('category.show')
            ->with([ 'categories'=>$categories, 'category'=>$category, 'drinks'=>$drinks ]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$category = Category::findOrFail($id);

		$user = Auth::user();
		if($category->user_id != $user->id) return response()->view('errors.404', [], 404);

		return view('category.edit')->with('category', $category);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$category = Category::findOrFail($id);

		$user = Auth::user();
		if($category->user_id != $user->id) return response()->view('errors.404', [], 404);

	    $this->validate($request, [
	        'name' => 'required'
	    ]);

		if($request->hasFile('image')) {
            $file = Input::file('image');
            $extension = Input::file('image')->getClientOriginalExtension();

            $name = 'category_' . $category->id . '.' . $extension;

            $category->image = '/images/' . $name;

            $file->move(public_path().'/images/', $name);
        }

	    $category->name = $request->get('name');

		$category->save();

		$drinks = $category->drinks()->get();
		$categories = \Auth::user()->categories()->get();

		return view('category.show')
            ->with([
				'categories'	=> $categories,
				'category'		=> $category,
				'drinks'		=> $drinks,
				'success' 		=> 'Categorie succesvol geupdated'
			]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$item = Category::findOrFail($id);

		$user = Auth::user();
		if($item->user_id != $user->id) return response()->view('errors.404', [], 404);

		$item->delete();

		return redirect('categories');
	}
}

www/resources/views/category/create.blade.php
@extends('layouts.backoffice', [ 'activeTab' => 'drinks' ])

@section('content')
<div class="container" style="padding: 20px">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Categorie</div>

                <div class="panel-body">
        			{!! Form::open(array('url' => 'categories', 'files' => true)) !!}
                    @if(count($errors))
                    <div class="form-group">
                        <div class="alert alert-danger">
                            <ul>
                                @foreach( $errors->all() as $error )
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    @endif
                    <div class="form-group">
            			{!! Form::label('name', 'Naam:') !!}
            			{!! Form::text('name',null,['class'=>'form-control']) !!}
            		</div>
                    <div class="form-group">
                        <div>
                            {!! Form::label('image', 'Achtergrond afbeelding:') !!}
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-lg-5">
                                <div class="well logo">
                                    <img class="img-responsive" id="src-image" src="">
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-7">
                                <a class="btn btn-warning" id="update-image" href>Kies een afbeelding</a>
                                <div class="hidden">
                                    {!! Form::file('image', ['id' => 'upload-image']) !!}
                                </div>
                            </div>
                        </div>
                    </div>
        		    <div class="form-group">
        		        {!! Form::submit('Maak een nieuwe categorie', ['class' => 'btn btn-primary form-control']) !!}
        		    </div>
        		    {!! Form::close() !!}
                </div>
            </div>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script>
$().ready(function(){
    // trigger click on hidden file input
    $('#update-image').on('click', function(){ $('#upload-image').click(); });

    // load choosen image
    $('#upload-image').change(function(){ srcImage(this, '#src-image'); });

    function srcImage(input, selector) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $(selector).attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
});
</script>
@endsection

www/resources/views/category/edit.blade.php
@extends('layouts.backoffice', [ 'activeTab' => 'drinks' ])

@section('content')
<div class="container" style="padding: 20px">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Deze categorie aanpassen</div>

                <div class="panel-body">
					{!! Form::model($category, [
						'method' => 'PATCH',
						'route' => ['categories.update', $category->id]
					]) !!}
                    <div class="form-group">
            			{!! Form::label('name', 'Naam:') !!}
            			{!! Form::text('name',null,['class'=>'form-control']) !!}
            		</div>
        		    <div class="form-group">
        		        {!! Form::submit('Save', ['class' => 'btn btn-primary form-control']) !!}
        		    </div>
        		    {!! Form::close() !!}
                </div>
            </div>
		</div>
	</div>
</div>
@endsection

www/resources/views/category/show.blade.php
@extends('layouts.backoffice', [ 'activeTab' => 'drinks', 'body' => ' categories ' ])

@section('content')

<div id="category-wrapper">
    <section id="categories">
        <section id="category-tabs">
            <ul class="c-horizontal-tabs">
                @foreach ($categories as $item)
                <li class="c-horizontal-tab {{ $item->id == $category->id ? 'is-active' : '' }}">
                    <a href="{{ route('categories.show', ['id' => $item->id]) }}" data-id="$item->id">{{ $item->name }}</a>
                </li>
                @endforeach
            </ul>
        </section>
        <section id="category-content">

                <div class="row">
                    <div class="col-sm-12">
                        {!! Form::open([
                            'method' => 'GET',
                            'route' => ['categories.create']
                        ]) !!}
                        <button class="button icon">
                            Voeg een nieuwe categorie toe
                            <i>
                                <svg preserveAspectRatio="xMidYMid meet" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="100%" viewBox="0 0 64 48.311" enable-background="new 0 0 64 48.311" xml:space="preserve">
                                <g>
                                  <polygon fill="#FFFFFF" points="24.474,48.311 0,23.844 8.798,15.042 24.474,30.711 55.181,0 63.98,8.8 	"/>
                                </g>
                                </svg>
                            </i>
                        </button>
                        {!! Form::close() !!}
                    </div>
                </div>

                <h2>{{ $category->name }}</h2>

                <div class="row top-buffer">
                    <div class="col-sm-6 col-sm-push-6">
                        <h3>Instellingen</h3>
                        <div class="row">
                            <div class="col-sm-12">
                                {!! Form::model($category, [
            						'method' => 'PATCH',
            						'route' => ['categories.update', $category->id],
                                    'files' => true
            					]) !!}
                                <div class="form-group">
                                    @if(isset($success))
                                    <div class="alert alert-success"> {{ $success }} </div>
                                    @endif
                                    <div class="alert-warning">
                                        @foreach( $errors->all() as $error )
                                           <br> {{ $error }}
                                        @endforeach
                                    </div>
                                </div>
                                <div class="form-group">
                        			{!! Form::label('name', 'Naam:') !!}
                        			{!! Form::text('name',null,['class'=>'form-control']) !!}
                        		</div>
                                <div class="form-group">
                                    <div>
                                        {!! Form::label('image', 'Achtergrond afbeelding:') !!}
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6 col-lg-5">
                                            <div class="well logo">
                                                <img class="img-responsive" id="src-image" src="{{ $category->image }}">
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-lg-7">
                                            <a class="btn btn-warning" id="update-image" href>Verander afbeelding</a>
                                            <div class="hidden">
                                                {!! Form::file('image', ['id' => 'upload-image']) !!}
                                            </div>
                                        </div>
                                    </div>
                    		    </div>
                    		    <div class="form-group">
                    		        {!! Form::submit('Opslaan', ['class' => 'btn btn-primary form-control']) !!}
                    		    </div>
                    		    {!! Form::close() !!}
                            </div>
                		</div>
                        <div class="row top-buffer">
                            <div class="col-sm-12">
                                {!! Form::open([
                                    'method' => 'DELETE',
                                    'route' => ['categories.destroy', $category->id]
                                ]) !!}
                                        <button type="submit" class="btn btn-danger">Verwijder deze categorie &nbsp;&nbsp;<i class="fa fa-trash" aria-hidden="true"></i></button>
                                {!! Form::close() !!}
                            </div>
                		</div>
                    </div>
                    <div class="col-sm-6 col-sm-pull-6">
                        <h3>Producten</h3>
                        <div class="row top-buffer">
                            <div class="col-sm-12">
                                <a class="btn btn-default btn-sm" href="{{ url('/drinks/create/'.$category->id) }}">Voeg een product toe</a>
                            </div>
                		</div>
                        <div class="row top-buffer">
                            <div class="col-sm-12">
                                @if ($drinks == null || count($drinks) < 1)
                                    <p></p>
                                    <p>
                                        Deze categorie heeft nog geen producten
                                    </p>
                                @else
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <td><b>Naam</b></td>
                                            <td><b>Prijs</b></td>
                                            <td></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($drinks as $drink)
                                        <tr>
                                            <td>{{ $drink->name }}</td>
                                            @if ($drink->promoted)
                                            <td><strike>{{ $drink->price }}</strike> {{ $drink->promoted_price }}</td>
                                            @else
                                            <td>{{ $drink->price }}</td>
                                            @endif
                                            <td align="right">
                                                {!! Form::open([
                                                    'method' => 'DELETE',
                                                    'route' => ['drinks.destroy', $drink->id]
                                                ]) !!}
                                                    <a class="btn btn-sm btn-primary" href="{{ URL::to('drinks/' . $drink->id . '/edit')}}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                    <button type="submit" class="btn btn-danger  btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                @endif
                            </div>
                		</div>
                    </div>
                </div>

                <div class="row top-buffer">
                    <div class="col-sm-12">

                    </div>
            	</div>
        </section>
    </section>
</div>
@endsection

@section('scripts')
<script>
$().ready(function(){
    // trigger click on hidden file input
    $('#update-image').on('click', function(){ $('#upload-image').click(); });

    // load choosen image
    $('#upload-image').change(function(){ srcImage(this, '#src-image'); });

    function srcImage(input, selector) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $(selector).attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
});
</script>
@endsection